name: Build and upload

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Nightly
      run: rustup toolchain install nightly --profile minimal
    - name: Set-up Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Upload
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{secrets.SERVER_SSH_IP}}
        username: debian
        key: ${{secrets.SERVER_SSH_KEY}}
        port: 22
        uploads: |
          ./target/release/ => ./
        ignore: |
          !mellow
